name: Build and deploy Node.js app to Azure Web App - my-react-app-99

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: CI=false npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A6FE18C4DD174C229B1015D1123079D6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_85F55CC12B0C46758899785FA1A3EB5A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7965F5D51F504C19946CDAA5B09242A5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'my-react-app-99'
          slot-name: 'Production'
          package: ./build
